data:
  trainDataPath: './datagrand/train.bioes'
  testDataPath: './datagrand/test.bioes'
  validDataPath: './datagrand/valid.bioes'
  wordDictSize: 25000
model:
  embeddingSize: 200
  hiddenSize: 100
  batchSize: 50
  epochNum: 500
  earlyStop: 20
  learningRate: 0.005
  modelSavePath: './datagrand/model.pkl'

