data:
  trainDataPath: './datagrand/train.bioes'
  validDataPath: './datagrand/test.bioes'
  submitDataPath: './datagrand/submit.change'
  wordDictSize: 25000
model:
  embeddingSize: 100
  hiddenSize: 100
  batchSize: 100
  epochNum: 2
  earlyStop: 10
  learningRate: 0.01
  bilstm:
    modelSavePath: './datagrand/bilstm/bilstm_model.pkl'
    submitPrePath: './datagrand/bilstm/submit_bilstm.reslut'
    submitResultPath: './datagrand/bilstm/submit_bilstm.txt'
  bilstm_crf:
    modelSavePath: './datagrand/bilstm/bilstm_crf_model.pkl'
    submitPrePath: './datagrand/bilstm/submit_bilstm_crf.reslut'
    submitResultPath: './datagrand/bilstm/submit_bilstm_crf.txt'
