data:
  trainDataPath: './datagrand/train.bioes'
  testDataPath: './datagrand/test.bioes'
  validDataPath: './datagrand/valid.bioes'
  wordDictSize: 25000
model:
  embeddingSize: 100
  hiddenSize: 100
  batchSize: 30
  epochNum: 500
  earlyStop: 20
  learningRate: 0.01
  modelSavePath: './datagrand/model.pkl'

