data:
  trainDataPath: './datagrand/train.bioes'
  testDataPath: './datagrand/test.bioes'
  validDataPath: './datagrand/valid.bioes'
  wordDictSize: 25000
model:
  embeddingSize: 100
  hiddenSize: 100
  batchSize: 50
  epochNum: 500
  earlyStop: 50
  learningRate: 0.001
  modelSavePath: './datagrand/model.pkl'

