data:
  trainDataPath: './datagrand/train.bioes'
  validDataPath: './datagrand/test.bioes'
  submitDataPath: './datagrand/submit.change'
  submitPrePath: './datagrand/submit_bilstm.result'
  submitResultPath: './datagrand/submit_bilstm.txt'
  wordDictSize: 25000
model:
  embeddingSize: 100
  hiddenSize: 100
  batchSize: 50
  epochNum: 50
  earlyStop: 10
  learningRate: 0.01
  modelSavePath: './datagrand/model.pkl'

